version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

jobs:
  buildanddeploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      #- run:
      #    name: Run linter
      #    command: npm run lint

      - run:
          name: Run tests
          command: npm run test
      
      - heroku/deploy-via-git

workflows:
  version: 2.1
  qualitygate_and_build:
    jobs:
      - buildanddeploy