version: 2

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to DockerHub
          command: |
            docker build --build-arg AUTH0_DOMAIN --build-arg AUTH0_CLIENT_ID --build-arg AUTH0_AUDIENCE -t hablijack/eilkurier-frontend:latest .
            docker login -username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASSWORD
            docker push hablijack/eilkurier-frontend:latest

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      #- qualitygate
      - build
