version: 2.1

jobs:
  cd:
    machine: true
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install --production

      - run:
          name: Build nuxt.js application
          command: npm run build

      #- run:
      #    name: Run linter
      #    command: npm run lint

      #- run:
      #    name: Run tests
      #    command: npm run test
      
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Setup Heroku CLI
          command: bash .circleci/setup-heroku.sh

      - run:
          name: push to heroku
          command: git push heroku main

workflows:
  version: 2
  frontendbuild:
    jobs:
      - cd:
          filters:
            branches:
              only: main