version: 2.1

jobs:
  cd:
    machine: 
      image: ubuntu-2004:202008-01
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build nuxt.js application
          command: npm run build

      #- run:
      #    name: Run linter
      #    command: npm run lint

      #- run:
      #    name: Run tests
      #    command: npm run test

      - run:
          name: push to heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/eilkurier.git main:master

workflows:
  version: 2
  frontendbuild:
    jobs:
      - cd:
          filters:
            branches:
              only: main