version: 2.1

jobs:
  buildanddeploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      #- run:
      #    name: Run linter
      #    command: npm run lint

      #- run:
      #    name: Run tests
      #    command: npm run test
      
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh


      - run:
          name: Setup Heroku CLI
          command: |
            bash .circleci/setup-heroku.sh
            git remote add heroku https://git.heroku.com/eilkurier.git

      - run:
          name: push to heroku
          command: git push heroku main

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - buildanddeploy:
          filters:
            branches:
              only: main