version: 2

jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to DockerHub
          command: |
            docker build --build-arg AUTH0_DOMAIN --build-arg AUTH0_CLIENT_ID --build-arg AUTH0_AUDIENCE -t hablijack/eilkurier-frontend:1.0.0 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/eilkurier-frontend:1.0.0

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      #- qualitygate
      - build
