version: 2.1

jobs:
  buildanddeploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      #- run:
      #    name: Run linter
      #    command: npm run lint

      #- run:
      #    name: Run tests
      #    command: npm run test
      
      - run:
          name: Install Heroku CLI
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            git remote add heroku https://git.heroku.com/eilkurier.git

      - run:
          name: Setup Heroku CLI
          command: bash .circleci/setup-heroku.sh

      - run:
          name: push to heroku
          command: |
            git push heroku main

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - buildanddeploy:
          filters:
            branches:
              only: main